### ISSUE TITLE
[Bug report] Null check operator used on a null value

### ISSUE THREAD

**Issue by coolight7** [fluttercandies/flutter_scrollview_observer#62]
### Version

1.18.0

### Platforms

dart

### Device Model

win 11

### flutter info

```sh
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [版本 10.0.22621.2428], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
```

### How to reproduce?

* 当组件在滚动过程中被销毁（比如这个列表正在滚动，然后页面返回，列表被销毁）时会出现这个报错
* 不过目前并没发现什么导致的异常情况，应该是小问题，无伤大雅。这个包真棒！

### Logs

```sh
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      Element.widget (package:flutter/src/widgets/framework.dart:3360:31)
#1      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:128:46)
#2      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3196:18)
#3      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3199:13)
#4      Element.dispatchNotification (package:flutter/src/widgets/framework.dart:4762:24)
#5      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
#6      ObserverControllerForScroll._handleScrollInterruption (package:scrollview_observer/src/common/observer_controller.dart:1073:46)
#7      ObserverControllerForScroll._handleScrollToIndex (package:scrollview_observer/src/common/observer_controller.dart:622:7)
#8      ObserverControllerForScroll._handleScrollToIndex.<anonymous closure> (package:scrollview_observer/src/common/observer_controller.dart:738:9)
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1236:9)
```

**Comment by LinXunFeng** [comment]
感谢老铁的反馈与支持，已发布 `1.18.1` 修复该问题
